apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - configuration.yaml
resources:
  - app.yaml
configMapGenerator:
  - name: app-b
    literals:
      - "PYROSCOPE_URL=http://pyroscope.observability:4040"
      - "OTEL_SERVICE_NAME=app-b"
      - "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo.observability:4318/v1/traces"
