apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: app-b-api
  description: API definition of app-b
spec:
  type: openapi
  owner: team-a
  lifecycle: production
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: app-b API
    servers:
    - url: https://app-b.127.0.0.1.nip.io
    paths:
      /:
        get:
          summary: Returns hello
