name: Build and Deploy application
on:
  push:
    branches:
      - main
jobs:
  publish_image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Check out app repository
        uses: actions/checkout@v3
      - name: Setup ko
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: docker.io/sselzer
      - name: Build Docker image and push
        run: |
          tag=$(echo  ${{ github.sha }} | cut -c -7) 
          ko login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p  ${{ secrets.DOCKER_PASSWORD }}
          ko build -B --platform=linux/amd64,linux/arm64 -t ${tag}
